[mcp_servers.blockbench]
url = "http://localhost:3000/bb-mcp"

[mcp_servers.mc-dev-assitant]
command = 'F:\mcpServer\WY-BE-MCP\mcdk-assistant\mcdk-assistant.exe'
args = ["--stdio"]

[mcp_servers.mc-wiki]
command = "node"
args = [
    'F:\mcpServer\Minecraft-Wiki-MCP\dist\server.js',
    "--api-url",
    "https://minecraft.wiki/api.php",
]
